### ISSUE TITLE
Typo: "Nob-Essential Instrumentation"

### ISSUE THREAD

**Issue by patlefort** [BBjaba/BAS-kernel#2]
In https://github.com/BBjaba/BAS-kernel/blob/7571481f8ad4274c81cd60471bbf85b9e4fa7d19/kernel/src/pciDescriptors.cpp#L26

Found it by random luck :)

**Comment by Bahamin-Shafaghi** [comment]
Oh. thx for finding it! I just got bored in writing that much class names :)
But it's better not to make a new issue for these sort of problems. It's better make a pull request.
